---
- ios_template:
    host: "{{ inventory_hostname }}"
    # The env var ANSIBLE_NET_PASSWORD and ANSIBLE_NET_USERNAME did not work
    # this variables can remove the need to especify password with cli
    #provider: "{{ cli }}"
    #After version 2.2 contains can be negated, update the waitfor.
    
    src: wan_edge_qos_acl.txt
