---
- name: "include {{ device_os }} tasks"
  include: "{{ outer_item }}"
  with_first_found:
    - files: "{{ device_os }}.yml"
      skip: true
      paths: tasks
  loop_control:
    loop_var: outer_item
